[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "Your_Site_ID"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = ""
  publish = "site/"
  command = "mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.7"
